/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Cabecalho: typeof import('./src/components/default/Cabecalho.vue')['default']
    CadastrarProduto: typeof import('./src/components/cadastro/CadastrarProduto.vue')['default']
    Carousel: typeof import('./src/components/Inicio/Carousel.vue')['default']
    Detalhamento: typeof import('./src/components/detalhamento/Detalhamento.vue')['default']
    DetalhamentoProdutos: typeof import('./src/components/detalhamento/DetalhamentoProdutos.vue')['default']
    ListagemDinamica: typeof import('./src/components/Inicio/ListagemDinamica.vue')['default']
    ListagemEstatica: typeof import('./src/components/Inicio/ListagemEstatica.vue')['default']
    Rodape: typeof import('./src/components/default/Rodape.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
