/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Cabecalho: typeof import('./src/components/default/Cabecalho.vue')['default']
    Carrousel: typeof import('./src/components/Inicio/Carrousel.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Rodape: typeof import('./src/components/default/Rodape.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
